### ISSUE TITLE
Possible bug, no plugin files written to project folder

### ISSUE THREAD

**Issue by karlmacklin** [nathanwoulfe/Clip#5]
Fresh install of Umbraco.

Clip initially added by adding the package to the csproj file and running `dotnet restore`.
As the "Content Creation Rules" section was unavailable, I removed the package reference and ran `dotnet restore`once again.

Then, Clip added by:
`dotnet add package Clip.Umbraco`
Project restarted.

Head into "Content Creation Rules" in Settings.

**Expected:**
See some settings or similar.

**Actual:**
![image](https://user-images.githubusercontent.com/353806/217809892-f51aef77-fec0-42e2-b996-1abf7ba83c8a.png)

**Also tried:**
As it was a new project, the folder App_Plugins was non-existant. I tried creating that folder, removed the package and added again.

I'm unsure if the possibly unorthodox way of initially adding the package ruined something in the setup? Either way, no template files available.

**Comment by nathanwoulfe** [comment]
Hey @karlmacklin, I thought I'd resolved this - I have a feeling it is a build issue where the static assets aren't included. 

There won't be an App_Plugins folder on disk as I'm using a Razor Class Library to serve embedded assets, but otherwise your CLI install + dotnet build should do the trick. 

I'll have a look at the build output today, and confirm if that's the cause.

**Comment by nathanwoulfe** [comment]
Just confirming too - which version are you installing? Build output for 10 and 11 looks fine, will try local installs and see if I can reproduce.

**Comment by karlmacklin** [comment]
> Just confirming too - which version are you installing? Build output for 10 and 11 looks fine, will try local installs and see if I can reproduce.

The very latest of v11 as of today, this was a new project we set up at work this morning.

At what point are you saying the files should be built? Maybe I'm missing a step. We usually just run Umbraco with dotnet run. Do we have to run something separate?

Not sure if relevant, but we had this problem on Mac (M1). Can test on Windows tomorrow.

**Comment by nathanwoulfe** [comment]
Try `dotnet build` before running - I've just installed locally into a clean Umbraco 11 site with no issues.

That said, `dotnet run` worked too... Could be Mac related, but not sure why that would matter given the cross-platform nature of dotnet.

**Comment by karlmacklin** [comment]
> Try `dotnet build` before running - I've just installed locally into a clean Umbraco 11 site with no issues.
> 
> That said, `dotnet run` worked too... Could be Mac related, but not sure why that would matter given the cross-platform nature of dotnet.

On a fresh install, with this package setup, it doesn't work on our M1 macbooks:
```
<ItemGroup>
    <PackageReference Include="Umbraco.Cms" Version="11.1.0" />
    <PackageReference Include="uSync" Version="11.0.1" />
    <PackageReference Include="Clip.Umbraco" Version="11.0.2" />
  </ItemGroup>
  ```

Windows works fine.

Can one see the actual html files somewhere in the project folder? I could perhaps compare if they exist in Windows context vs Mac context.
I've searched the project folder for overview.html for example but no go.

**Comment by markadrake** [comment]
I came here to ditto what's been reported above. When running the latest versions (LTS) of Umbraco and this package, there is a 404 error in the backoffice trying to reach "overview.html".  I'm running on Apple silicon, too.

This is the original request, and it fails:

`/App_Plugins/Clip/backoffice/contentCreationRules/overview.html`

This is the updated request, and it works:

`/App_Plugins/Clip/Backoffice/contentCreationRules/overview.html`

We've encountered many of these issues since moving to .NET Core with Umbraco. The Linux file system is case-sensitive. The fix above is capitalization, "B"ackoffice.

**Comment by markadrake** [comment]
When I renamed "Backoffice" to "backoffice," this ended up creating a 404 for "clip.min.js."  Once I fixed this reference, the dashboard loads again:

![image](https://github.com/nathanwoulfe/Clip/assets/713355/2b2ec1c1-7391-4ab4-9286-d0c55f7ed057)

**Comment by nathanwoulfe** [comment]
Hey @markadrake I'll get to this, I promise.

**Comment by markadrake** [comment]
I promise I'm not being lazy—it seems like a simple change but I seem to recall doing something like this before (change the case of a folder) and the change not truly propagating down (perhaps only affecting Windows).

Thanks @nathanwoulfe!

**Comment by nathanwoulfe** [comment]
I've published a 10.1.1, 12.0.1 and 13.0.1 which should resolve this - found a couple of spots where casing differed for `Backoffice`, fixed em up, Linux et al should be happy. Releases will be landing on Nuget shortly.

**Comment by jasonhilldm** [comment]
I've just tried adding the package using dotnet add package Clip.Umbraco and then ran dotnet build but am still getting the same 404 error. I am running VS code on Apple silicon too and have installed v13.0.1 of the Clip package.

NOTE: This is only happening when running the site locally though - when the site is deployed then it works fine.
